"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./features/components/Header";
import Footer from "./features/components/Footer";
import { useRef } from "react";


const companyName = "Navyugam";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const metadata: Metadata = {
  title: "Navyugam",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footerRef = useRef<HTMLDivElement | null>(null);

  const scrollToFooter = () => {
      footerRef.current?.scrollIntoView({behavior: 'smooth'});
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >  
         <Header  onContactClick={scrollToFooter} />
         <main className="flex-1">
          {children}</main>
         <Footer ref={footerRef} companyName={companyName} />
         
      </body>
    </html>
  );
}
