version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: robodb
      POSTGRES_USER: robouser
      POSTGRES_PASSWORD: robopasswordstrong
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
  static_data:
  media_data:
