# Generated by Django 5.2.1 on 2025-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competition_info',
            field=models.TextField(blank=True, help_text='Additional competition information and guidelines'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_area_description',
            field=models.TextField(blank=True, help_text='Description of the event area/arena'),
        ),
        migrations.AddField(
            model_name='event',
            name='gameplay_rules',
            field=models.TextField(blank=True, help_text='Detailed rules for gameplay'),
        ),
        migrations.AddField(
            model_name='event',
            name='how_to_register',
            field=models.TextField(blank=True, help_text='Step-by-step guide on how to register for the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_for_robo_building',
            field=models.TextField(blank=True, help_text='Specific rules and guidelines for building the robot'),
        ),
    ]
