# Generated by Django 5.2.1 on 2025-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdate',
            name='image',
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the image accompanying the news update.', null=True),
        ),
    ]
