# Generated by Django 5.2.1 on 2025-05-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='banner_video_url',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='banner_video',
            field=models.FileField(blank=True, help_text='Upload the main banner video file (mp4, webm, etc.).', null=True, upload_to='banner_videos/'),
        ),
    ]
